---
- hosts: elevate
  vars:
    project_path: /opt/frontend/solution-upload-portal-2
    root_path: /opt/frontend
  tasks:
    - name: Slurp host file
      slurp:
        src: "/opt/backend/deployment/.token"
      register: slurpfile

    - name: Run vault credentials
      shell: "curl --location --request GET '{{ vaultAddress }}solution-upload-portal-2' --header 'X-Vault-Token: {{ slurpfile['content'] | b64decode }}' | jq '.data' > '{{root_path}}/data2.json'"
      register: vaultCurl

    - name: Delete old project directory
      file:
        path: "{{ project_path }}"
        state: absent

    - name: Recreate project directory
      file:
        path: "{{ project_path }}"
        state: directory
        mode: '0755'
        recurse: yes

    - name: Fetch the latest code
      git:
        repo: https://github.com/ELEVATE-Project/solution-upload-portal
        dest: "{{project_path}}"
        version: "{{gitBranch}}"
        force: yes

    - name: Update npm
      shell: cd {{project_path}} && npm i --force

    - name: Set permission
      shell: chmod 744 {{ project_path }}/src/scripts/json2env.sh

    # - name: Generate env.js from Vault JSON
    #   shell: |
    #     echo 'window["env"] = ' > {{ project_path }}/src/assets/env.js
    #     cat {{ root_path }}/data2.json | jq '.data' >> {{ project_path }}/src/assets/env.js
    #   args:
    #     executable: /bin/bash

    - name: Generate environment.ts
      shell: |
        cat {{root_path}}/data2.json | jq '.data' > {{ project_path }}/src/environments/environment.ts &&
        sed -i '1s/^/export const environment = \n/' {{ project_path }}/src/environments/environment.ts
      register: envConfig
        
    - name: Change directory
      shell: chdir {{project_path}}
    - name: Fetch pm2 config file
      shell: "curl --location --request GET '{{ vaultAddress }}solutionPortalPm2Config2' --header 'X-Vault-Token: {{ slurpfile['content'] | b64decode }}' | jq '.data.data' > '{{ project_path }}/pm2.config.json'"
      register: pm2
    - name: Change directory
      shell: cd {{project_path}}
    # - name: Remove www folder
    #   shell: rm -rf www
    # - name: Build pwa app
    #   shell: cd {{project_path}} && ng build --prod
    # - name: Start pm2
    #   shell: cd {{project_path}} && pm2 start pm2.config.json
    - name: Delete old pm2 process
      command: pm2 delete solution-upload-portal-2
      ignore_errors: yes

    - name: Start pm2 with config
      shell: cd {{project_path}} && pm2 start "npx ng serve --port 4202 --host 0.0.0.0 --disable-host-check" --name solution-upload-portal-2
